
USE `goulm`;
-- Create table
create table TRACELOG
(
  `OPTID`  int(11) NOT NULL AUTO_INCREMENT,
  LOGINUSER  varchar(20)  CHARACTER SET utf8 DEFAULT NULL,
  OPT_URL    varchar(80)  CHARACTER SET utf8 DEFAULT NULL,
  OPT_NAME   varchar(80) CHARACTER SET utf8 DEFAULT NULL,
  ORG_PARAMS varchar(2080) CHARACTER SET utf8 DEFAULT NULL,
  OPT_TIME   timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  OPT_RESULT varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  FROM_IP varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`OPTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;